# GridSearch

**Crea un 'iterador' de parámetros para el ajuste de modelos, permitiendo acceder a los valores más  óptimos**

In [13]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import numpy as np
boston = load_boston()
X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.25, random_state=33)

In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

reg_tree = DecisionTreeRegressor()
param_grid = {
        'max_depth' : [2,4,6],
        'max_features' : [2, 4, 6, 8]
}

**sklearn.model_selection.GridSearchCV**

- **estimator:** This is assumed to implement the scikit-learn estimator interface. (model)
- **param_grid:** Dictionary with parameters names (string) as keys and lists of parameter settings to try as values
- **scoring:** Evaluate the predictions on the test set
- **cv:** Cross validation splitting strategy (default 3-fold cross validation)
- **return_train_score:** If _false_ the **cv_results_** attribute will not include training scores

In [35]:
grid_search = GridSearchCV(reg_tree, param_grid, scoring='neg_mean_squared_error', cv=5, return_train_score=True)

In [36]:
grid_search.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [2, 4, 6], 'max_features': [2, 4, 6, 8]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='neg_mean_squared_error', verbose=0)

## Propiedades del GridSearch

**GridSearchCV.best_estimator_:** estimator that was choosen by the search, i.e. estimator which gave the highest score (or smallest loss if specified) on left out data.

It returns the model with the best parameters for the prediction

In [37]:
grid_search.best_estimator_

DecisionTreeRegressor(criterion='mse', max_depth=6, max_features=4,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

**GridSearchCV.best_score_:** Mean cross-validated score of the **best_estimator**

In [38]:
grid_search.best_score_

-19.797622545683318

**GridSearch.best_params_:** Dictionary with the parameter setting that gave the best results on the hold data.

In [39]:
grid_search.best_params_

{'max_depth': 6, 'max_features': 4}

**grid_search.cv_results_['mean_train_score']:** returns all the mean values for the score in each combination of parameters

In [40]:
grid_search.cv_results_['mean_train_score']

array([-40.14262846, -36.44427852, -28.32199958, -30.27151783,
       -24.82713245, -14.50994094, -13.79179231, -10.96419161,
       -16.02694269,  -5.47125492,  -5.60971103,  -4.59882782])

**Now for example we can calculate the RMSE for the train set**

the negative sign is because we define the scoring parameter as **neg_mean_squared_error**

In [41]:
np.sqrt(-grid_search.cv_results_['mean_train_score'])

array([6.33582106, 6.03690968, 5.32184175, 5.50195582, 4.98268326,
       3.80919164, 3.71373024, 3.31122207, 4.00336642, 2.33907138,
       2.36848285, 2.14448778])

**We can also check the scores for the test set**

Is logic if the test scores are higher than the train scores, because thos eare new values that are beign evaluated

In [42]:
np.sqrt(-grid_search.cv_results_['mean_test_score'])

array([6.90960601, 7.49131975, 6.13748953, 6.26450647, 6.46062035,
       5.24794327, 6.32983921, 4.75581824, 6.45228186, 4.44945194,
       5.44755613, 4.52805588])

# RandomizedSearch

**---------------------------------------------**
### Pregunta: Diferencia entre cv y n_iter      |
**--------------------------------------------**

**Muy similar al _GridSearch_, pero en este caso los valores son creados aleatoreamente desde un rango definido**

RandomizedSearchCV(estimator, param_distributions, n_iter=10, scoring=None, n_jobs=None, iid=’warn’, refit=True, cv=’warn’, verbose=0, pre_dispatch=‘2*n_jobs’, random_state=None, error_score=’raise-deprecating’, return_train_score=False)

In [19]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint

In [43]:
param_grid = {
    'max_depth' : sp_randint(2,6),
    'max_features' : sp_randint(2,8)
}

In [44]:
rand_search = RandomizedSearchCV(reg_tree, param_distributions=param_grid, cv=5, n_iter=10, scoring='neg_mean_squared_error', return_train_score=True)

In [45]:
rand_search.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
          fit_params=None, iid='warn', n_iter=10, n_jobs=None,
          param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000024AEE33BFD0>, 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000024AEE3FA160>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring='neg_mean_squared_error',
          verbose=0)

In [46]:
rand_search.best_params_

{'max_depth': 3, 'max_features': 7}

In [47]:
rand_search.best_estimator_

DecisionTreeRegressor(criterion='mse', max_depth=3, max_features=7,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [29]:
# Comparamos los resultados entre Randomizedsearch y GridSearch
print("Promedio GridSearch RMSE: ", np.sqrt(-grid_search.cv_results_['mean_test_score']).mean())
print("Promedio RandomizedSearch RMSE: ", np.sqrt(-rand_search.cv_results_['mean_test_score']).mean())

Promedio GridSearch RMSE:  5.807233064973158
Promedio RandomizedSearch RMSE:  6.13752002895376


# Cambiando el scoring de GridSearch

In [49]:
param_grid = {'max_depth' : [2,4,6], 'max_features' : [2,4,6,8]}
grid_search_r2 = GridSearchCV(reg_tree, param_grid, cv=5, scoring='r2', return_train_score=True)

In [51]:
grid_search_r2.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [2, 4, 6], 'max_features': [2, 4, 6, 8]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

## Evaluación en test set

In [52]:
from sklearn.metrics import mean_squared_error

In [54]:
y_pred_gs = grid_search.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred_gs))

6.273634068195198

In [55]:
y_pred_rs = rand_search.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred_rs))

5.477773039088486

In [56]:
y_pred_r2 = grid_search_r2.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred_r2))

6.836980126908566